name: Listfiles

on: [push, workflow_dispatch]

jobs:
  files_data:
    name: list files
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: pip intall python

      - name: check pyhton
        run: python --version || python -v  