name: Listfiles

on: [push, workflow_dispatch]

jobs:
  files_data:
    name: list files
    runs-on: ubuntu-latest
    steps:
       - name: Set up Python 3.11
         uses: actions/setup-python@v5
         with:
          python-version: '3.11'

       - name: check pyhton
         run: python --version